INSERT INTO Universities (name, location, website, description, ranking, img_data)
VALUES 
	('King Salman International University', 'Ras Sider, South Sinai', 'https://ksiu.edu.eg/', 'King Salman International University is envisioned as a prestigious institution of higher learning, dedicated to fostering academic excellence, research, and innovation on an international scale. Situated in a strategic location, the university aims to attract students and faculty from diverse backgrounds and nationalities, creating a vibrant and multicultural learning environment. At King Salman International University, students have access to a wide range of undergraduate, graduate, and professional programs designed to meet the evolving needs of the global workforce. The curriculum is crafted to provide students with a well-rounded education, combining theoretical knowledge with practical skills and real-world experiences.', 1, (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\king salman.jpg', SINGLE_BLOB) AS image_data)),
    ('Al Alamein University', 'Al Alameen City, Marsa Matrouh', 'https://aiu.edu.eg/', 'Al Alamein University is a leading institution of higher education located in the coastal city of Al Alamein, Egypt. Nestled along the pristine shores of the Mediterranean Sea, the university offers a unique and picturesque setting for academic pursuits. Committed to excellence in education, research, and innovation, Al Alamein University provides a diverse range of undergraduate and graduate programs across various disciplines. Whether in the fields of arts and humanities, sciences, engineering, business, or health sciences, students at Al Alamein University benefit from a rigorous curriculum taught by esteemed faculty members who are experts in their fields.', 2, (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\download (2).jpeg', SINGLE_BLOB) AS image_data)),
	('Galala University', 'Attaka, Suiz', 'https://www.gu.edu.eg/', 'Galala University is a private institution located in the city of Suez, Egypt. Established in 2019, Galala University aims to provide high-quality education across various disciplines, with a focus on innovation, research, and community engagement. Galala University offers a diverse range of undergraduate and graduate programs designed to meet the needs of students and the demands of the modern workforce. From engineering and technology to business, humanities, and social sciences, the university provides students with opportunities to pursue their academic interests and career aspirations.', 3 ,(SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\download.jpeg', SINGLE_BLOB) AS image_data)),
    ('New Mansoura University', 'New Mansoura City, Dakahlia', 'https://www.nmu.edu.eg/ar', 'At New Mansoura University, research and innovation are central to its mission. The university encourages faculty and students to engage in cutting-edge research projects that address pressing societal challenges and contribute to the advancement of knowledge in their respective fields. Through collaborations with industry partners, government agencies, and international institutions, the university seeks to promote innovation and entrepreneurship and drive economic development in the region.', 4, (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\new_mansoura.jpg', SINGLE_BLOB) AS image_data)),
	('The Egyptian E-Learning University', 'Dokki, Giza', 'https://www.eelu.edu.eg/en/', 'The Egyptian E-Learning University (EELU) is a pioneering institution of higher education in Egypt that specializes in providing online and distance learning programs. Established with the aim of expanding access to quality education and catering to the diverse needs of students, EELU offers a wide range of undergraduate and graduate programs across various disciplines. EELU utilizes cutting-edge technology and innovative teaching methods to deliver high-quality education to students regardless of their geographical location or personal circumstances. Through its online platform, students have the flexibility to study at their own pace and convenience, allowing them to balance their academic pursuits with work, family, and other commitments.', 5,   (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\The_Egyptian_E-Learning.jpg', SINGLE_BLOB) AS image_data)),
	('Al Nile University', 'El Sheikh Zayed, Giza', 'https://nu.edu.eg/', 'Nile University is a prestigious institution of higher education located in Cairo, Egypt. At Nile University, students benefit from a dynamic and stimulating learning environment characterized by modern facilities, state-of-the-art laboratories, and technologically advanced classrooms. Nile University places a strong emphasis on research and innovation, encouraging faculty and students to engage in cutting-edge research projects that address local and global challenges. ', 6,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Al_Nile.jpg', SINGLE_BLOB) AS image_data)),
	('The French University in Egypt', '21 Ismailia Desert Road Ville Shorouk, Cairo', 'https://ufe.edu.eg/', 'At the French University in Egypt, students have the opportunity to pursue undergraduate and graduate programs in various disciplines, including engineering, business, humanities, social sciences, and more. One of the distinctive features of the French University in Egypt is its bilingual education system. Courses are taught in both French and Arabic, allowing students to develop proficiency in both languages while gaining a deeper understanding of their subject matter. This bilingual approach not only enhances students linguistic abilities but also fosters cross-cultural exchange and understanding.', 7, (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\The_French_university.jpg' , SINGLE_BLOB) AS image_data)),
    ('Egypt University of Information', 'New Administrative Capital, Cairo', 'https://eui.edu.eg/', 'The Egypt University of Information (EUI) is a pioneering institution dedicated to advancing knowledge, technology, and innovation in the field of information science and technology. Situated in the heart of Egypt, EUI offers a comprehensive range of undergraduate and graduate programs designed to equip students with the skills, expertise, and creativity needed to thrive in the rapidly evolving digital landscape. With state-of-the-art facilities, cutting-edge research centers, and a faculty of renowned scholars and industry experts, EUI provides students with a dynamic learning environment that fosters critical thinking, problem-solving, and hands-on experience. Committed to excellence in education, research, and community engagement, EUI serves as a hub for collaboration, innovation, and transformative change, shaping the future of information technology and empowering individuals to make a meaningful impact in Egypt and beyond.', 8,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Egypt_University_of_Information.png', SINGLE_BLOB) AS image_data)),
    ('Helwan National University', 'Halwan, Cairo', 'http://www.hnu.edu.eg/', 'This university aims to support the journey of higher education and scientific research through the provision of specialized educational programs adhering to international academic standards, and in alignment with fourth-generation smart universities, to meet the needs of the job market for new graduates equipped with modern cognitive and technological capabilities locally, regionally, and internationally. With a forward-looking vision and planning in collaboration with specialized international universities to support the advancement of students and researchers from within the university, and to support the Egyptian society in achieving national goals', 9,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\halwan_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('Mansoura National University', 'Belbes, Dakahlia', 'https://www.mansnu.edu.eg', 'This university is like any other national university that is recently built in Egypt that have the same aim and is working towards biulding a well prepared students for the future and to give them hands-on experiance so they can lead a better future for the country. But it is built in Mansoura to make it easier for all Mansoura students to get the same education quality as any other university.', 10,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Mansoura_uni.png', SINGLE_BLOB) AS image_data)),
    ('Benha National University', 'Al Obour main avenue, Obour City', 'https://bnu.edu.eg/', 'Benha National University is located on Al Obour main avenue in Obour City. As one of Egyptian leading institutions of higher education, it offers a wide range of academic programs designed to meet the needs of students and the demands of the job market. The university is committed to academic excellence, research, and community engagement, providing students with the knowledge and skills needed to succeed in their chosen fields.', 11,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Benha_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('Menoufia National University', 'Cairo-Alexandria Agriculture Road, Egypt', 'https://mnu.menofia.education/', 'Menoufia National University, situated on Cairo-Alexandria Agriculture Road in Egypt, is dedicated to providing high-quality education and fostering innovation and research. With a focus on interdisciplinary learning and hands-on experience, the university prepares students for success in a rapidly changing world.', 12,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Menoufia_uni.jpg', SINGLE_BLOB) AS image_data)),
	('Beni Suef National University', 'New Beni Suef City, Beni Suef', 'https://nu.bsu.edu.eg/', 'Beni Suef National University, located in New Beni Suef City, Beni Suef, is committed to promoting academic excellence and research-driven education. The university offers a diverse range of programs and opportunities for students to engage in cutting-edge research and innovation.', 13,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Beni _Suef_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('Assiut National University', 'New Assiut City, Assiut', 'http://www.asnu.edu.eg/', 'Assiut National University, situated in New Assiut City, Assiut, is dedicated to advancing knowledge, fostering innovation, and serving the needs of society. With a strong emphasis on research and community engagement, the university prepares students to become leaders and changemakers in their fields.', 14,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\assuit_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('South Valley National University', 'Qism Qena, Qena', 'http://svnu.edu.eg/', 'South Valley National University, located in Qism Qena, Qena, is committed to providing students with a comprehensive education that prepares them for success in a globalized world. The university offers a supportive learning environment and encourages students to pursue their passions and interests.', 15, (SELECT BulkColumn FROM OPENROWSET(BULK  'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\South_Valley_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('Minia National University', 'New Minya, Red Sea', 'https://www.minia.edu.eg/Minia/desofnew.aspx?new_id=618338', 'Minia National University, situated in New Minya, Red Sea, is dedicated to excellence in education, research, and community service. The university provides students with opportunities for intellectual growth, personal development, and engagement with pressing societal issues.', 16,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Minia_ni.jpg', SINGLE_BLOB) AS image_data)),
    ('East Port Said National University', 'Al Salam City, Port Said', 'https://www.facebook.com/epsu.edu.eg/', 'East Port Said National University, located in Al Salam City, Port Said, is committed to academic excellence and research-driven education. The university offers a supportive learning environment and encourages students to explore their interests and pursue their goals.', 17,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\East_Port_Said_uni.jpg', SINGLE_BLOB) AS image_data)),
    ('Alexandria National University', 'AL Raml, Alexandria', 'https://www.alexu.edu.eg/index.php/????-???????/8187-???-???-??????-??????-??????-??????????-???????', 'Alexandria National University, situated in Al Raml, Alexandria, is dedicated to advancing knowledge and fostering innovation in a diverse range of disciplines. With a strong emphasis on research and community engagement, the university prepares students to become leaders and innovators in their fields.', 18,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\Alexandria_National_Uni.png', SINGLE_BLOB) AS image_data)),
    ('Zagazig National University', '10th Of Ramadan, Sharqia', 'https://m.facebook.com/ZagazigNationalUniversity', 'Zagazig National University, located in 10th Of Ramadan, Sharqia, is committed to academic excellence and research-driven education. The university offers a supportive learning environment and encourages students to pursue their passions and interests.', 19,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\zagazig_uni.png', SINGLE_BLOB) AS image_data)),
    ('New Ismailia National University', 'New Ismailia City, Ismailia', 'http://ninu.edu.eg/', 'New Ismailia National University, situated in New Ismailia City, Ismailia, is dedicated to providing high-quality education and fostering innovation and research. With a focus on interdisciplinary learning and hands-on experience, the university prepares students for success in a rapidly changing world.', 20,  (SELECT BulkColumn FROM OPENROWSET(BULK 'C:\Users\moham\OneDrive\Documents\GitHub\ahlia-project\static\images\New_Ismailia_uni.jpg', SINGLE_BLOB) AS image_data));



INSERT INTO Programs (university_id, name, description)
VALUES 
    (1, 'Engineering Sciences ', '1- Architecture Engineering Program, 2- Electronics and Communications Engineering Program, 3- Energy Engineering Program, 4- Mechatronics Engineering Program, 5- Engineering and Construction Management Program'),
    (1, 'Computer Engineering', '1- Embedded Systems, 2- Cloud Computing, 3- High-Performance Computing, 4- Cybersecurity, 5- Artificial Intelligence Engineering Program'),
    (1, 'Computer Science', ' 1- Biomedical Informatics Program, 2- Computer Science Program (including tracks: Big Data Analysis, Computational Linguistics, Software Engineering, Artificial Intelligence Sciences Program)'),
	(1, 'Technological Industries', ' 1- Refrigeration and Air Conditioning Technology Program, 2- Production Industry Technology Program, 3- Microdevice Industry Technology Program '),
	(1, 'Advanced Basic Sciences', ' 1- Molecular Biotechnology Program, 2- Petroleum Chemistry Program '),
	(1, 'Desert Agriculture', 'Plant Production Program in Arid Regions '),
	(1, 'Veterinary Medicine', 'Veterinary Medicine Program '),
	(1, 'Medicine', 'Medicine and Surgery Program '),
	(1, 'Dentistry', 'Dentistry Program '),
	(1, 'Pharmaceutical Science', 'PharmD Program: Clinical Pharmacy '),
	(1, 'Nursing ', 'Nursing Sciences Program '),
	(1, 'Administrative and Business Sciences', '1- Investment and Finance Program, 2- Accounting and Information Systems Program '),
	(1, 'Applied Languages', '1- Editorial and Instant Translation Program in English, 2- Editorial and Instant Translation Program in German '),
	(1, 'Tourism and Hospitality', 'Hotel and Resort Management Program '),
	(1, 'Arts and Design', '1- Interior Architecture Program, 2- Graphic Design and Brand Building Program '),
	
	(2, 'Engineering', '1- Architectural Design and Digital Architecture, 2-Biomedical Engineering, 3- Biomedical Engineering in collaboration with the University of Louisville, 4- Petroleum and Gas Engineering, 5- Mechatronics Engineering, 6- Construction Engineering and Management, 7- Communications and Electronics Engineering'),
	(2, 'Computer Engineering', '1- Computer Engineering ( 1- Embedded Systems and IoT track, 2- Cloud Computing track, 3- High-Performance Computing track, 4- Computer Security track), 2- Computer Engineering in collaboration with the University of Louisville, 3- Artificial Intelligence Engineering  '),
	(2, 'Computer Science', '1- Computer Science in collaboration with the University of Louisville, 2-Computer Science Program (Big Data Analysis - Computer Vision - Software Engineering), 3-Artificial Intelligence Sciences Program '),
	(2, 'Advanced Basic Sciences', '1- Molecular Biotechnology Program, 2-Sustainable Energy Program '),
	(2, 'Public Health', 'Public Health Program '),
	(2, 'Dentistry', 'Dentistry Program'),
	(2, 'Pharmaceutical Sciences', 'PharmD Program '),
	(2, 'Administrative Sciences and Business', '1- Accounting and Information Systems, 2- Logistics Management and Supply Chains, 3- Marketing '),
	(2, 'Arts and Design', '1- Advertising and Communication Program in collaboration with Lyon 3 University, 2- Interior Design Program, 3- Graphic Design and Brand Building Program '),
	
	(3, 'Engineering Sciences', ' 1- Architectural Design, Digital Architecture, and Environmental Architecture, 2- Mechatronics and Industrial Automation Engineering, 3- Electrical Engineering, granting a dual degree, 4- Materials Engineering and Manufacturing '),
	(3, 'Computer Engineering', '1- Embedded Systems, 2- Cloud Computing, 3- High-Performance Computing, 4- Cybersecurity, 5- Artificial Intelligence Engineering program '),
	(3, 'Computer Sciences', 'Computer Science program, ( 1- Biomedical Informatics track, 2- Big Data Analysis track, 3- Computer Vision track, 4- Software Engineering track, 5- Artificial Intelligence Sciences, 6- Software Engineering program granting a dual degree)'),
	(3, 'Advanced Basic Sciences', '1- Molecular Biotechnology program, 2- Petroleum and Mining Geology, 3- Nanoscience and Technology program '),
	(3, 'Applied Health Sciences', '1- Applied Medical Technology, including 1- Radiology Technology, 2- Medical Imaging, 3- Prosthetic and Orthotic Technology, 4- Medical Laboratory Technology, 5- Dental Manufacturing Technology. '),
	(3, 'Medicine', ' 1- Medicine and Surgery program, 2- Dentistry program, 3- Pharmaceutical Sciences program (Pharma D), 4- Physiotherapy program, 5- Nursing Sciences program '),
	(3, 'Administrative Sciences and Business', ' 1- Marketing program, 2- Business Administration program, 3- Information Systems program, 4- Economics and Political Science program, 5- Logistics and Supply Chains program and all with dual degrees with the University of Arizona, USA. '),
	(3, 'Applied Languages', '1- Japanese Language program, 2- Media Production program ( 1- Advertising Production track, 2- Television Production track'),
	(3, 'Arts and Design', ' 1- Interior Architecture program, 2- Clothing and Textile Manufacturing program, 3- Graphic Design program'),
	(3, 'Physical Therapy', 'Physical Therapy Program'),
	
	(4, 'Administrative Sciences and Business', '1- Entrepreneurship and Innovation program, 2- Management program, 3- Finance and Investment program, 4- Marketing program, 5- Logistics and Supply Chain program, 6- Economics and Political Science program, 7- Accounting and Information Systems program '),
	(4, 'International Legal Transactions', '1- International Legal Transactions program'),
	(4, 'Engineering ', '1- Media Technology Engineering program, 2- Civil Engineering Technology Implementation program, 3- Product Development Engineering program, 4- Aerospace Engineering program, 5- Petroleum and Gas Engineering program, 6- Environmental Architecture and Construction Technology program, 7- Mechatronics Engineering program, 8- Energy Engineering program, 9- Biomedical Engineering program '),
	(4, 'Computer Science', '1- Big Data Analysis track, 2- Computer Vision track, 3- Software Engineering track, 4- Biomedical Informatics program, 5- Artificial Intelligence Sciences program'),
	(4, 'Computer Engineering', '1- Embedded Systems track, 2- Cloud Computing track, 3- High-Performance Computing track, 4- Cybersecurity track, 5- Artificial Intelligence Engineering program '),
	(4, 'Sciences ', '1- Industrial Chemistry program, 2- Molecular Biology program, 3- Forensic Sciences program, 4- Molecular Biotechnology program '),
	(4, 'Medicine ', 'Medicine and Surgery program '),
	(4, 'Dentistry ', 'Dentistry program '),
	(4, 'Pharmaceutical Sciences', 'Pharmacy program (Pharma D - Clinical Pharmacy)'),
	(4, 'Textile Science and Engineering', '1- Textile Materials Science and Engineering program,  2- Polymer Chemistry and Color Engineering for Textiles program, 3- Clothing and Textile Marketing and Management program, 4- Textile Design and Fashion program '),
	(4, 'Applied Health Sciences', '1- Medical Laboratory Technology program, 2- Radiology and Medical Imaging Technology program, 3- Dental Manufacturing Technology program, 4- Anesthesia and Intensive Care Technology program, 5- Respiratory Therapy program, 6- Prosthetics and Orthotics Technology program, 7- Occupational Therapy program, 8- Optometry Technology program '),
	(4, 'Nursing Sciences ', '1- Nursing Sciences program ( 1- Emergency Nursing track, 2- Addiction Nursing track, 3- Midwifery Nursing track, 4- Neonatal Nursing track )'),
	
	(5, 'Computer Science and Information Technology', ' Computer Science and Information Technology'),
	(5, 'Business Administration and Commercial Studies', 'Management ( 1- Marketing, 2- Accounting, 3- Finance and Investment, 4- E-commerce, 5- Management Information Systems )'),
	(5, 'Education Studies', 'The student will a degree in ( 1- General Educational Diploma, 2- Vocational Educational Diploma, 3- Special Educational Diploma, 4- Master of E-Learning )'),

	(6, 'Engineering and Applied Sciences', '1- Architecture and Urban Design, 2- Civil and Infrastructure Engineering and Management, 3- Electronics and Computer Engineering, 4- Industrial Engineering, 5- Mechanical Engineering'),
	(6, 'Business Administration', '1- Logistics Management and Supply Chains, 2- Integrated Marketing Communication, 3- Finance, 4- Economics, 5- General Business and Entrepreneurship'),
	(6, 'Information Technology and Computer Science', '1- '),
	(6, 'Biotechnology', '1- Applied Biotechnology, 2- Bioinformatics'),

	(7, 'Mechanical Engineering', 'Mechanical Engineering'),
	(7, 'Architecture', 'Sustainable Development'),
	(7, 'International Relations', 'International Relations Program'),
	(7, 'Applied Languages', 'APPLIED LANGUAGES French and English Program'),
	(7, 'Economics and Management', 'Economics and Management Program'),
	(7, 'Computer Engineering', '1- Computing, 2- artificial intelligence'),
	
	(8, 'Computer Science and Information', '1- Computer Science, 2- Cybersecurity, 3- Computer Graphics and Electronic Game Programming, 4- Artificial Intelligence, 5- Data Science and Engineering, 6- Software Engineering '),
	(8, 'Engineering', '1- Electronics and Communications Engineering, 2- Computer Engineering, 3- Industrial Engineering, 4- Mechatronics Engineering'),
	(8, 'Business Technology', '1- Finance, 2- Accounting, 3- Business Analysis, 4- Management of Business Technology, 5- Digital Marketing and E-commerce, 6- Entrepreneurship and Innovation'),
	(8, 'Digital Arts and Design', '1- Interactive Design, 2- Animation, 3- Electronic Game Design, 4- Contemporary Media Arts, 5- Graphic Design, 6- User Experience Design'),
	
	(9, 'Engineering', '1- Smart Systems Engineering Program, 2- Architecture and Environmental Design Program'),
	(9, 'Arts and Applied Arts', '1- Environmental Interior Design Program, 2- Animation and Visual Effects Program'),
	(9, 'Humanities, Commerce, and Business Administration', 'Business Informatics and Digital Transformation Program'),

	(10, 'Medicine', 'Medicine and Surgery Program'),
	(10, 'Engineering', '1- Civil Engineering, 2- Biomedical Engineering, 3- Artificial Intelligence Engineering, 4- Communications and Computer Engineering, 5- Mechatronics Engineering, 6- Sustainable Architecture Engineering '),
	(10, 'Dentistry', 'Dentistry and Oral Surgery'),
	(10, 'Economics and Administrative Sciences', '1- Business Administration and International Relations, 2- Electronic Entrepreneurship, 3- Economics and Finance, 4- Legal Accounting, 5- Digital Marketing and E-commerce, 6- Engineering Business Management'),
	(10, 'Pharmacy', 'Pharm-D Clinical Program'),
	(10, 'Nursing', 'Nursing Science program'),

	(11, 'Medicine', 'Medicine Program'),
	(11, 'Dentistry', 'Dentistry Program'),
	(11, 'Physical Therapy', 'Physical Therapy Program'),
	(11, 'Engineering', '1- Manufacturing and Materials Engineering, 2- Mechatronics and Automation Engineering, 3- Communication Systems Engineering, 4- Biomedical Engineering, 5- Construction Engineering, 6- Housing and Community Design'),
	(11, 'Computer Science', '1- Artificial Intelligence and Machine Learning, 2- Computational Linguistics, 3- Data Science, 4- Software Development and Applications, 5- Virtual and Augmented Reality'),
	(11, 'Economics and Business Administration', '1- Business Management and International Relations, 2- Statistics and Insurance, 3- Digital Marketing and E-Business, 4- International Economics and Finance, 5- Accounting and Business Informatics'),

	(12, 'Human Medicine', 'Medicine Program'),
	(12, 'Dentistry', 'Dentistry Program'),
	(12, 'Veterinary Medicine', 'Veterinary Medicine Program'),
	(12, 'Applied Health Sciences Technology', 'Applied Health Sciences Technology Program'),
	(12, 'Physical Therapy', 'Physical Therapy Program'),
	(12, 'Engineering', 'Engineering Program'),
	(12, 'Pharmacy', 'Pharmacy Program'),
	(12, 'Computer Science and Artificial Intelligence', 'Computer Science and Artificial Intelligence Program'),
	(12, 'Nursing', 'Nursing Program'),
	(12, 'Humanities', 'English Language and Specialized Translation Program'),

	(13, 'Human Medicine', 'Medicine and Surgery Program'),
	(13, 'Dentistry', 'Dentistry and Oral Surgery Program'),
	(13, 'Physical Therapy', 'Physical Therapy Program'),
	(13, 'Engineering', '1- New and Sustainable Energy Program, 2- Architectural Design and Digital Architecture Program'),
	(13, 'Media', 'Television and Film Production Program'),
	(13, 'Computer Science and Artificial Intelligence', '1- Artificial Intelligence and Data Science Program, 2- Cybersecurity Engineering Program, 3- Medical Informatics Program'),
	(13, 'Arts', '1- Clinical Psychology Program, 2- Surveying and Mapping Program, 3- Information Systems Program'),
	(13, 'Science', 'Materials Science and Nanotechnology Program'),
	(13, 'Commerce', 'Business Systems and Information Program'),
	(13, 'Nursing', 'Nursing Program'),
	(13, 'Navigation Science and Space Technology', 'Applied Space Science and Navigation Program'),

	(14, 'Human Medicine', 'Medicine Program'),
	(14, 'Dentistry', 'Dentistry Program'),
	(14, 'Pharmacy and Pharmaceutical Research', 'Pharmacy and Pharmaceutical Research Program'),
	(14, 'Engineering and Applied Sciences', 'Engineering and Applied Sciences Program'),
	(14, 'Computer Science and Artificial Intelligence', 'Computer Science and Artificial Intelligence Program'),
	(14, 'Financial and Administrative Sciences', 'Financial and Administrative Sciences Program'),
	(14, 'Linguistics and Applied Languages', 'Linguistics and Applied Languages Program'),

	(15, 'Medicine and Surgery', 'Medicine and Surgery Program'),
	(15, 'Physical Therapy', 'Physical Therapy Program'),
	(15, 'Computer Science and Artificial Intelligence', 'Computer Science and Artificial Intelligence Program'),
	(15, 'Nursing', 'Nursing Program'),
	(15, 'Pharmacy', 'Pharmacy Program'),
	(15, 'Engineering', 'Engineering Program'),

	(16, 'Medicine', 'Medicine Program'),
	(16, 'Dentistry', 'Dentistry Program'),
	(16, 'Pharmacy ', 'Pharm D Clinical Pharmacy Program'),
	(16, 'Physiotherapy', 'Physiotherapy Program'),
	(16, 'Engineering ', 'Mechatronics and Industrial Robotics Engineering Program'),
	(16, 'Computers and artificial intelligence', 'Computers and artificial intelligence Program'),
	(16, 'Public Relations and Business Administration', 'Advertising and Public Relations Program'),

	(17, 'Medicine and Surgery', 'Medicine and Surgery Progarm'),
	(17, 'Dentistry ', 'Dentistry Progarm'),
	(17, 'Pharmacy ', 'Pharmacy Progarm'),
	(17, 'Computer Engineering', 'Computer Engineering Progarm'),
	(17, 'Physical Therapy', 'Physical Therapy Progarm'),
	(17, 'Health sciences', 'Health sciences Progarm'),
	(17, 'Computer Science', 'Computer Science Progarm'),
	(17, 'Administrative Sciences', 'Administrative Sciences Progarm'),
	(17, 'Nursing', 'Nursing Program'),

	(18, 'Medicine and Surgery', 'Medicine Medicine and Surgery Program'),
	(18, 'Dentistry', 'Dentistry Oral and Dental Medicine and Surgery Program'),
	(18, 'Pharmacy', 'Pharma D - Clinical Program'),
	(18, 'Computer and Communication Engineering', '1- Mechatronics and Robotics Engineering Program, 2- Architecture and Construction Program, 3- Cyber Security Program, 4- Smart Systems Program, 5- Electromechanical Engineering Program'),
	(18, 'Petroleum Engineering', 'Petroleum Engineering Program'),
	(18, 'Computer Science', '1- Data Science Program, 2- Software and Multimedia Industry Program'),
	(18, 'Business Administration Science', '1- Banking and Finance Program, 2- Management Program, 3- Marketing Program, 4- Sensory and Information Systems Program, 5- Geomatics and Surveying Studies Program'),
	(18, 'Media Production', '1- Digital Media Program, 2- program phonetics and linguistics'),

	(19, 'Medicine and Surgery', 'Medicine and General Surgery Program'),
	(19, 'Oral and Dental Medicine and Surgery', 'Oral and Dental Medicine and Surgery Program'),
	(19, 'Engineering', '1- Mechatrotics Program, 2- Structural Engineering and Construction Management programs'),
	(19, 'Computers and Information', '1- Artificial Intelligence and Data Science Program, 2- Medical Informatics Program, 3- Aviation Information Systems Program'),
	(19, 'Commerce', '1- Accounting Program, 2- Business Administration, 3- Marketing Program'),
	
	(20, 'Medicine', 'Medicine Program'),
	(20, 'Dentistry', 'Dentistry Program'),
	(20, 'Pharmacy', '1- Pharma D Program - Clinical Pharmacy, 2- Pharmacy Program'),
	(20, 'Physical Therapy', 'Physical Therapy Program'),
	(20, 'Nursing', 'Nursing Program'),
	(20, 'Applied Health Sciences Technology', 'Applied Health Program'),
	(20, 'Engineering and Construction', 'Engineering and Construction Program'),
	(20, 'International Trade and Languages', '1- Financial Markets and Institutions, 2- Translation in German, Literature, English and Chinese, 3- Digital Marketing and E-Business program');

INSERT INTO AdmissionRequirements (requirement)
VALUES 
    ('Original copy of high school diploma certificate. 4 passport-sized photos with white background. Copy of national ID card for Egyptian students, and passport photo for non-Egyptian students. Original copy of military service forms 2, 6, 7 for male applicants in universities. Certificate of passing the Arabic language test for foreign applicants. Original copy of TOEFL or IELTS certificate for Egyptian students. Receipt confirming payment of all tuition fees.');
   
INSERT INTO Fees (program_id, description, amount)
VALUES 
--galala
    (30, 'Tuition fees for the Faculty of Medicine at Galala University.', 120000.00),
    (30, 'Tuition fees for the Faculty of Pharmacy at Galala University.', 85000.00),
    (30, 'Tuition fees for the Faculty of Dentistry at Galala University.', 107000.00),
    (31, 'Tuition fees for the Faculty of Social and Human Sciences at Galala University.', 43000.00),
    (30, 'Tuition fees for the Faculty of Physiotherapy at Galala University.', 70000.00),
    (26, 'Tuition fees for the Faculty of Engineering at Galala University.', 69000.00),
    (27, 'Tuition fees for the Faculty of Computer Science at Galala University.', 69000.00),
    (28, 'Tuition fees for the Faculty of Basic Sciences at Galala University.', 48000.00),
    (26, 'Tuition fees for the Faculty of Computer Engineering at Galala University.', 69000.00),
    (30, 'Tuition fees for the Faculty of Nursing Sciences at Galala University.', 31000.00),
    (32, 'Tuition fees for the Faculty of Media Production at Galala University.', 50000.00),
    (31, 'Tuition fees for the Faculty of Administrative Sciences at Galala University.', 46000.00),
    (29, 'Tuition fees for the Faculty of Applied Health Sciences at Galala University.', 39000.00),
    (33, 'Tuition fees for the Faculty of Arts and Design at Galala University.', 49000.00),

--zagazig
    (137, 'Tuition fees for the Faculty of Human Medicine at Zagazig National University.', 140000.00),
    (138, 'Tuition fees for the Faculty of Dentistry at Zagazig National University.', 110000.00),
    (139, 'Tuition fees for the Faculty of Engineering at Zagazig National University.', 55000.00),
    (140, 'Tuition fees for the Faculty of Computer Science at Zagazig National University.', 40000.00),

--king salman
    (8, 'Tuition fees for the Faculty of Human Medicine at King Salman University.', 105000.00),
    (9, 'Tuition fees for the Faculty of Dentistry at King Salman University.', 97000.00),
    (7, 'Tuition fees for the Faculty of Veterinary Medicine at King Salman University.', 60000.00),
    (11, 'Tuition fees for the Faculty of Nursing Sciences at King Salman University.', 31000.00),
    (10, 'Tuition fees for the Faculty of Pharmacy at King Salman University.', 85000.00),
    (2, 'Tuition fees for the Faculty of Engineering and Computing at King Salman University.', 69000.00),
    (1, 'Tuition fees for the Faculty of Architecture Engineering at King Salman University.', 69000.00),
    (13, 'Tuition fees for the Faculty of Textile Sciences and Engineering at King Salman University.', 58000.00),
    (15, 'Tuition fees for the Faculty of Arts at King Salman University.', 49000.00),
    (6, 'Tuition fees for the Faculty of Desert Agriculture at King Salman University.', 43000.00),
    (5, 'Tuition fees for the Advanced Basic Sciences Faculty at King Salman University.', 48000.00),
    (14, 'Tuition fees for the Faculty of Tourism and Hospitality at King Salman University.', 40000.00),

--ismailia
    (142, 'Tuition fees for the Faculty of Human Medicine at Ismailia National University.', 95000.00),
    (143, 'Tuition fees for the Faculty of Dentistry at Ismailia National University.', 85000.00),
    (144, 'Tuition fees for the Faculty of Pharmacy at Ismailia National University.', 65000.00),
    (148, 'Tuition fees for the Faculty of Engineering at Ismailia National University.', 55000.00),
    (146, 'Tuition fees for the Faculty of Nursing at Ismailia National University.', 25000.00),
    (147, 'Tuition fees for the Faculty of Applied Health Sciences Technology at Ismailia National University.', 25000.00),
    (149, 'Tuition fees for the Faculty of International Trade and Languages at Ismailia National University.', 25000.00),

--benha
    (73, 'Tuition fees for the Faculty of Human Medicine at Benha University.', 90000.00),
    (76, 'Tuition fees for the Faculty of Engineering at Benha University.', 90000.00),
    (77, 'Tuition fees for the Faculty of Computer Science and Artificial Intelligence at Benha University.', 45000.00),
    (78, 'Tuition fees for the Faculty of Economics and Business Administration at Benha University.', 45000.00),

--Al Alamein
    (22, 'Tuition fees for the Faculty of Pharmacy at Al Alamein University.', 94000.00),
    (21, 'Tuition fees for the Faculty of Dentistry at Al Alamein University.', 107000.00),
	(20, 'Tuition fees for the Faculty of Public Health at Al Alamein University.', 63000.00),
    (16, 'Tuition fees for the Faculty of Engineering at Al Alamein University.', 72000.00),
    (18, 'Tuition fees for the Faculty of Computer Science at Al Alamein University.', 72000.00),
    (17, 'Tuition fees for the Faculty of Computer Engineering at Al Alamein University.', 72000.00),
    (19, 'Tuition fees for the Faculty of Advanced Basic Sciences at Al Alamein University.', 51000.00),
    (23, 'Tuition fees for the Faculty of Administrative Sciences at Al Alamein University.', 49000.00),
    (24, 'Tuition fees for the Faculty of Arts and Design at Al Alamein University.', 52000.00),

--New Mansoura
    (41, 'Tuition fees for the Faculty of Medicine at New Mansoura University.', 105000.00),
    (42, 'Tuition fees for the Faculty of Dentistry at New Mansoura University.', 97000.00),
	(46, 'Tuition fees for the Faculty of Nursing at New Mansoura University.', 31000.00),
    (38, 'Tuition fees for the Faculty of Computer Science at New Mansoura University.', 69000.00),
    (39, 'Tuition fees for the Faculty of Computer Engineering at New Mansoura University.', 69000.00),
    (40, 'Tuition fees for the Faculty of Advanced Basic Sciences at New Mansoura University.', 48000.00),
    (45, 'Tuition fees for the Faculty of Applied Health Sciences at New Mansoura University.', 39000.00),
    (43, 'Tuition fees for the Faculty of Pharmaceutical Sciences at New Mansoura University.', 85000.00),

--Mansoura
    (67, 'Tuition fees for the Faculty of Medicine at Mansoura National University.', 110000.00),
    (69, 'Tuition fees for the Faculty of Dentistry at Mansoura National University.', 90000.00),
	(72, 'Tuition fees for the Faculty of Nursing at Mansoura National University.', 30000.00),
    (68, 'Tuition fees for the Faculty of Engineering at Mansoura National University.', 56000.00),
    (70, 'Tuition fees for the Faculty of Economics and Administrative Sciences at Mansoura National University.', 30000.00),
    (71, 'Tuition fees for the Faculty of Pharmacy at Mansoura National University.', 75000.00),

--Asyuit
    (103, 'Tuition fees for the Faculty of Engineersing at Assiut National University.', 45000.00),
    (102, 'Tuition fees for the Faculty of Pharmacy at Assiut National University.', 55000.00),
    (100, 'Tuition fees for the Faculty of Medicine at Assiut National University.', 90000.00),
    (101, 'Tuition fees for the Faculty of Dentistry at Assiut National University.', 75000.00),
    (104, 'Tuition fees for the Faculty of Computer Science and Artficial Intellegance at Assiut National University.', 40000.00),

--beni suif
    (89, 'Tuition fees for the Faculty of Medicine at Beni Suef National University.', 85000.00),
    (94, 'Tuition fees for the Faculty of Computer Science and Artficial Intellegance at Beni Suef National University.', 40000.00),
    (90, 'Tuition fees for the Faculty of Dentistry at Beni Suef National University.', 70000.00),
    (91, 'Tuition fees for the Faculty of Physiotherapy at Beni Suef National University.', 60000.00),
    (92, 'Tuition fees for the Faculty of Engineering at Beni Suef National University.', 55000.00),
    (96, 'Tuition fees for the Faculty of Science at Beni Suef National University.', 30000.00),
    (98, 'Tuition fees for the Faculty of Nursing at Beni Suef National University.', 25000.00),
    (97, 'Tuition fees for the Faculty of Bussiness admin at Beni Suef National University.', 30000.00);